[package]
name = "simi"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = "0.25"
image = "0.24"
aes-gcm = "0.10"
rsa = {version = "0.7", features = ["serde"]}
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
toml = "0.5"
home = "0.5"
bincode = "1.3"
colored = "2.0"
